server:
  port: 9501
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: http://localhost:9501


zuul:
  routes:
    cloudnote-user-service: /user/**
    cloudnote-blog-service: /blog/**
    cloudnote-crowd-service: /crowd/**
    cloudnote-comment-service: /comment/**
  ignored-services:
    "*"
spring:
  application:
    name: cloudnote-zuul-9501