spring:
  application:
    name: cloudnote-comment-serivce
  profiles:
    include:
      - eureka-client
      - mybatis-plus
      - sleuth
      - web
      - zipkin-client
server:
  port: 8004
eureka:
  instance:
    instance-id: http://localhost:8004
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
info:
  app.name: CloudNote-Comment-Serivce
  company.name: www.kould.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
