server:
  port: 8601
spring:
  application:
    name: cloudnote-sleuth-8601

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: http://localhost:8601
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false